on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Fetch the previous commit to compare with

      - name: Get Cargo.toml versions
        id: get_versions
        run: |
          current_version=$(grep -oE 'version = "[^"]+"' Cargo.toml | cut -d '"' -f 2)
          previous_version=$(git show HEAD^1:Cargo.toml | grep -oE 'version = "[^"]+"' | cut -d '"' -f 2)
          echo 'current_version=$current_version' >> "$GITHUB_OUTPUT"
          echo 'previous_version=$previous_version' >> "$GITHUB_OUTPUT"
          echo '$current_version'
          echo '$previous_version'

      - name: Compare version numbers
        id: compare_versions
        run: |
          if [[ "${{ steps.get_versions.outputs.current_version }}" != "${{ steps.get_versions.outputs.previous_version }}" ]]; then
            echo "Version changed!"
            echo 'version_changed=true' >> "$GITHUB_OUTPUT"
          else
            echo "Version unchanged."
            echo 'version_changed=false' >> "$GITHUB_OUTPUT"
          fi

      # Run additional tasks if version changed
      - name: Install stable toolchain (for publishing)
        if: steps.compare_versions.outputs.version_changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish
        if: steps.compare_versions.outputs.version_changed == 'true'
        run: |
          cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}