on:
  push:
    branches:
      - main
  workflow_dispatch:


name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Get previous Cargo.toml contents
        run: |
          if [[ "${{ github.event_name }}" == 'push' ]]; then
            previous_cargo_toml_contents=$(git cat-file -p HEAD^1:Cargo.toml)
          else
            previous_cargo_toml_contents=$(git cat-file -p "${{ github.event.before }}":Cargo.toml)
          fi
          echo "${previous_cargo_toml_contents}" >> $GITHUB_STATE

      - name: Extract version numbers
        run: |
          current_cargo_toml_contents=$(cat Cargo.toml)
          previous_cargo_toml_contents=$(cat $GITHUB_STATE)
          echo "Current Cargo.toml contents:"
          echo "$current_cargo_toml_contents"
          echo "Previous Cargo.toml contents:"
          echo "$previous_cargo_toml_contents"
          current_version=$(echo "$current_cargo_toml_contents" | grep -oE 'version = "[^"]+"' | cut -d '"' -f 2)
          previous_version=$(echo "$previous_cargo_toml_contents" | grep -oE 'version = "[^"]+"' | cut -d '"' -f 2)
          echo "Current version: $current_version"
          echo "Previous version: $previous_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
          echo "previous_version=$previous_version" >> $GITHUB_OUTPUT

      - name: Compare version numbers
        run: |
          if [[ "${{ env.current_version }}" != "${{ env.previous_version }}" ]]; then
            echo "Version changed!"
          else
            echo "Version unchanged."
          fi