on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Build and Upload

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Add debug step to see what's in pyproject.toml
    - name: Debug pyproject.toml
      run: |
        echo "=== pyproject.toml content ==="
        cat pyproject.toml
        echo "=== End pyproject.toml ==="
    
    - name: Build wheels first (without upload)
      uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release --out dist
        maturin-version: "1.4.0"
    
    # Debug the generated metadata
    - name: Debug wheel metadata
      run: |
        python -c "
        import zipfile
        import glob
        
        wheel_files = glob.glob('dist/*.whl')
        print(f'Found wheels: {wheel_files}')
        
        if wheel_files:
            with zipfile.ZipFile(wheel_files[0], 'r') as z:
                metadata_files = [f for f in z.namelist() if f.endswith('/METADATA')]
                print(f'Metadata files: {metadata_files}')
                
                if metadata_files:
                    metadata = z.read(metadata_files[0]).decode('utf-8')
                    print('=== METADATA content ===')
                    for i, line in enumerate(metadata.split('\n')[:20]):
                        print(f'{i+1:2d}: {repr(line)}')
                    print('=== End METADATA ===')
        "
    
    # Only upload if we want to see the debug info first
    # Comment this out for the first run to see debug output
    # - name: Upload to PyPI
    #   uses: PyO3/maturin-action@v1
    #   env:
    #     MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    #   with:
    #     command: upload
    #     args: dist/*