on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Fetch the previous commit to compare with

      - name: Get Cargo.toml versions
        id: get_versions
        run: |
          cv=$(grep -oE 'version = "[^"]+"' Cargo.toml | cut -d '"' -f 2)
          previous_version=$(git show HEAD^1:Cargo.toml | grep -oE 'version = "[^"]+"' | cut -d '"' -f 2)
          echo 'current_version=$cv' >> "$GITHUB_ENV"
          echo 'previous_version=$previous_version' >> "$GITHUB_ENV"

      - name: Compare version numbers
        id: compare_versions
        run: |
          if [[ "$current_version" != "$previous_version" ]]; then
            echo "Version changed!"
            echo 'version_changed=true' >> "$GITHUB_ENV"
          else
            echo "Version unchanged."
            echo 'version_changed=false' >> "$GITHUB_ENV"
          fi

      # Run additional tasks if version changed
      - name: Install stable toolchain (for publishing)
        if: '$version_changed' == 'true'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish
        if: '$version_changed' == 'true'
        run: |
          cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}